---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/carcajcl/public_html/wp-content/themes/carcaj
    - /bin/rm -rf $DEPLOYPATH/* # Limpia el directorio destino
    - /bin/cp -R ./* $DEPLOYPATH # Copia los nuevos archivos
